## **Theoretical Questions:**

1. **Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?**

Ans: Numpy is a foundation library in python for numerical and scientific computing, primarily because it enhance python's capablilities in handiling large, multidimensional array and matrices, along with providing a varity of mahemetical functions.

**Purpose of NumPy:**
1. Efficient Array Processing: NumPy provides a powerful object, the ndarray, which allows for fast and efficient processing of large datasets. It supports arrays of any dimension and data type.
2. Mathematical Operations: NumPy includes a wide range of functions for mathematical operations like linear algebra, statistical operations, Fourier transforms, and more.
3. Interfacing with Other Libraries: NumPy serves as a foundation for other scientific computing libraries in Python, like SciPy, Pandas, and scikit-learn, all of which build on its data structures and routines.

**Advantages of NumPy:**
A. Performance: NumPy is highly optimized, as it’s implemented in C, which makes operations on arrays much faster than using Python's native lists. Vectorized operations, which process entire arrays at once, eliminate the need for loops in many cases, leading to substantial speedups.

B. 50X faster then list in python
C.  Manipulation and accessing of element are very very easy
D. continous storing of array Locality of reference
E. very useful for performing logical and mathematical calculations on array and matrix.

**How NumPy Enhances Python’s Capabilities:**

A. Providing Fast Array Operations: NumPy’s array-based computing is faster than Python’s native lists due to its C-based implementation, making it suitable for high-performance tasks.

B. Enabling Data Interoperability: NumPy arrays are a standard data format, facilitating data exchange between various Python libraries.

2. ** Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?**

Ans:

**np.mean()  :**

1. use to calculate arithmetic mean
2. all element have equal weight
3. weight cannot be passed through the parameter of the given function.
4. **syntax**
    np.mean(arr,axis=None)
ex:

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.mean(arr))

3.0


**np.average() **
1. use to calculate the artihmetic mean as well as weight average.
2. all element may or may not have equal weight.
3. weight can be passed through the parameter of the given function.
4. **syntax**
    numpy.average(arr, axis=None, weight = none)

ex:

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array : ",arr,"\n")
print("Mean of the Array : ",np.average(arr),"\n")
weight = np.array([4,5,6,12,15,10,2,8,19,20])
print("Weight average of Array : ",np.average(arr, weights=weight))

Array :  [ 1  2  3  4  5  6  7  8  9 10] 

Mean of the Array :  5.5 

Weight average of Array :  6.574257425742574


3.**Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.**

Ans: **Reversing a 1D array**


In [3]:
import numpy as np

arr_1d = np.array([1,2,3,4,5,6])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)

[6 5 4 3 2 1]


**Reversing a 2D array **

In [4]:
# 2D array example
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


 **Reverse Along Both Axes (180-degree Rotation)**

In [5]:
reversed_both_axes = arr_2d[::-1, ::-1]
print(reversed_both_axes)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


4. ** How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.**

Ans: Numpy array is a multi-dimensional data structure that is the core of scientific computing in python.

all values in array are homogenous .

**Dimensions in array**
0D(zero dimensional): for example scalar- a single element

1D (one- Dimension): for example vector- a list of integer

2D (two- Dimensional): for example matrix - a spreadsheet of data

3D(three-Dimensional): for example tensor-storing a color image.

**Create a Array Object:**
Numpy array's object allow us to work with arrays in python. the array object is called ndarray.

array() function of the Numpy library creates a ndarray.

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


5. ** Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**


Ans: array in numpy is a table of element(usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array. A tuple of integers giving the size of the array along each dimension is known as shape of the array, An array class in numpy is called as ndarray.

element in numpy array are accessed by using square brackets and can be initilized by using nested python list.

ex: [[1,2,3],[4,3,1]]
here, rank = 2 , 1st dimension length = 2, 2nd dimension has length = 3
overall shape can be expressed (2,3)

**importent point of list**

1. the list can be homogeneous or heterogoneous.
2. element wise operation is not possible on the list.
3. python list is by default 1D. But we can create an N-D list. but then too it will be 1D list strong another 1D list
4. element of a list need not be contiguous in memory.

**Comparison between Numpy array and Python List**

1. **Element Overhead:** Lists in Python store additional information about each element, such as its type and reference count. This overhead can be significant when dealing with a large number of elements.

2. **Datatype:** Lists can hold different data types, but this can decrease memory efficiency and slow numerical operations.

3. **Memory Fragmentation:** Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.


6. ** Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations**

Ans:
**Memory Efficiency**
Homogeneous Data Storage: NumPy arrays are typed, meaning all elements have the same data type, allowing them to be stored in contiguous memory blocks. This differs from Python lists, which can store mixed data types, requiring separate references for each element. The result is lower memory overhead and better memory locality in NumPy.

**peed of Element-wise Operations**
Vectorization: NumPy supports vectorized operations, allowing operations to be applied to entire arrays without the need for explicit loops. This leads to significantly faster execution since the underlying operations are implemented in C and run at compiled speeds. In contrast, Python lists require iteration through each element, which is slower and more computationally intensive.

**Optimized Mathematical and Statistical Functions**
NumPy offers a range of highly optimized functions for mathematical and statistical operations (e.g., np.sum, np.mean, np.dot). These functions are often implemented in lower-level languages, like C or Fortran, and they take advantage of optimized linear algebra libraries (e.g., BLAS, LAPACK).

**Performance Comparison: NumPy Array vs. Python List**

In [1]:
import numpy as np
import time

# Large dataset
n = 10_000_000
list_data = list(range(n))
array_data = np.array(list_data)

# Using a Python list
start_time = time.time()
list_squared = [x**2 for x in list_data]
print("Time taken using list:", time.time() - start_time, "seconds")

# Using a NumPy array
start_time = time.time()
array_squared = array_data**2
print("Time taken using NumPy array:", time.time() - start_time, "seconds")


Time taken using list: 4.708946466445923 seconds
Time taken using NumPy array: 0.05474591255187988 seconds


7. ** Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output**

Ans:
vstack( vertical stack):
Purpose: Stack arrays vertically, along rows. It concatenates arrays along the first axis (axis=0).
Requirements: Arrays must have the same number of columns to stack vertically.

Example:

In [2]:
import numpy as np

# Creating two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Using vstack
result_vstack = np.vstack((array1, array2))
print("Result of vstack:\n", result_vstack)


Result of vstack:
 [[1 2 3]
 [4 5 6]]


hstcak(horizontal stack):
Purpose: Stack arrays horizontally, along columns. It concatenates arrays along the second axis (axis=1).
Requirements: Arrays must have the same number of rows to stack horizontally.

In [3]:
# Creating two 1D arrays
array5 = np.array([1, 2, 3])
array6 = np.array([4, 5, 6])

# Using hstack
result_hstack = np.hstack((array5, array6))
print("Result of hstack:\n", result_hstack)


Result of hstack:
 [1 2 3 4 5 6]


8. **Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.**

Ans:
**fliper(): flip left to right (horizontal flip)**

*  fliplr() flips an array along its horizontal axis, effectively reversing the order of columns for each row.

* fliplr() only works with arrays that have two or more dimensions (i.e., it requires at least two columns in the array).

example with a 2D array

In [4]:
import numpy as np

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Using fliplr
flipped_lr = np.fliplr(array_2d)
print("Result of fliplr:\n", flipped_lr)


Result of fliplr:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


**flipud(): Flip Up to Down (Vertical Flip)**

* flipud() flips an array along its vertical axis, reversing the order of rows.
* flipud() works with arrays of any dimension that have at least one row.

example with 2D array

In [5]:
# Using flipud
flipped_ud = np.flipud(array_2d)
print("Result of flipud:\n", flipped_ud)


Result of flipud:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


9. ** Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

Ans: Array splitting in NumPy is like a slice of cake. Think of each element in a NumPy array as a slice of cake. Splitting divides this “cake” into smaller “slices” (sub-arrays), often along specific dimensions or based on certain criteria. We can split horizontally, vertically, or even diagonally depending on our needs.

**key concept:**
1. Axis: The dimension along which the array is split (e.g., rows, columns, depth).
2. Sub-arrays: The smaller arrays resulting from the split.
3. Splitting methods: Different functions in NumPy for splitting arrays (e.g., np.split(), np.vsplit(), np.hsplit(), etc.).
4. Equal vs. Unequal splits: Whether the sub-arrays have the same size or not.


In [7]:
import numpy as np
Arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(Arr, 3)
print(array)

[array([1, 2]), array([3, 4]), array([5, 6])]


**Splitting NumPy Arrays in Python**
a. Split numpy array using numpy.split()
b. Split numpy array using numpy.array_split()
c. Splitting NumPy 2D Arrays
d. Split numpy array using numpy.vsplit()
e. Split numpy array using numpyhsplit()
f. Split numpy arrayusing numpy.dsplit()

9. **. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?**

Ans:
**Numpy array Broadcasting:**
Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. This is because NumPy is implemented in C Programming, which is a very efficient language.
It does this without making needless copies of data which leads to efficient algorithm implementations. But broadcasting over multiple arrays in NumPy extension can raise cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows down the computation.

**Array Broadcasting Examples**

In [8]:
import numpy as np
a = np.array([17, 11, 19]) # 1x3 Dimension array
print(a)
b = 3
print(b)

# Broadcasting happened because of
# miss match in array Dimension.
c = a + b
print(c)

[17 11 19]
3
[20 14 22]


**Vectorized in Numpy:**
Numpy arrays are homogeneous in nature means it is an array that contains data of a single type only. Python’s lists and tuples are unrestricted in the type of data they contain. The concept of vectorized operations on NumPy allows the use of more optimal and pre-compiled functions and mathematical operations on NumPy array objects and data sequences. The Output and Operations will speed up when compared to simple non-vectorized operations.

In [9]:
import numpy as np
import timeit

# vectorized sum
print(np.sum(np.arange(15000)))

print("Time taken by vectorized sum : ", end = "")
%timeit np.sum(np.arange(15000))

# iterative sum
total = 0
for item in range(0, 15000):
    total += item
a = total
print("\n" + str(a))

print("Time taken by iterative sum : ", end = "")
%timeit a

112492500
Time taken by vectorized sum : 15.4 µs ± 557 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

112492500
Time taken by iterative sum : 33.5 ns ± 0.72 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


# **Practical Questions:**

1. ** Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [10]:
import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", array_3x3)

# Step 2: Interchange rows and columns (transpose)
transposed_array = array_3x3.T
print("\nTransposed Array (Rows and Columns Interchanged):\n", transposed_array)


Original Array:
 [[ 4 60 92]
 [98 41 52]
 [84 66 67]]

Transposed Array (Rows and Columns Interchanged):
 [[ 4 98 84]
 [60 41 66]
 [92 52 67]]


2. **Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [11]:
import numpy as np

# Step 1: Generate a 1D array with 10 elements
array_1d = np.arange(10)
print("Original 1D Array:\n", array_1d)

# Step 2: Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:\n", array_2x5)

# Step 3: Reshape the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)
print("\nReshaped to 5x2 Array:\n", array_5x2)


Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. ** Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [12]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", array_4x4)

# Step 2: Add a border of zeros to make it a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:\n", array_6x6)


Original 4x4 Array:
 [[0.0130501  0.17191684 0.45241517 0.85956703]
 [0.74143569 0.12585818 0.91296296 0.72766313]
 [0.27972072 0.93568837 0.30834397 0.85559401]
 [0.16382443 0.35783319 0.63906795 0.96490331]]

6x6 Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.0130501  0.17191684 0.45241517 0.85956703 0.        ]
 [0.         0.74143569 0.12585818 0.91296296 0.72766313 0.        ]
 [0.         0.27972072 0.93568837 0.30834397 0.85559401 0.        ]
 [0.         0.16382443 0.35783319 0.63906795 0.96490331 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. **Using NumPy, create an array of integers from 10 to 60 with a step of 5**

Ans:

In [13]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array:", array)


Array: [10 15 20 25 30 35 40 45 50 55 60]


5. ** Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

In [14]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply uppercase transformation
uppercase_array = np.char.upper(array)
print("Uppercase:", uppercase_array)

# Apply lowercase transformation
lowercase_array = np.char.lower(array)
print("Lowercase:", lowercase_array)

# Apply title case transformation
titlecase_array = np.char.title(array)
print("Title Case:", titlecase_array)

# Capitalize the first letter only
capitalize_array = np.char.capitalize(array)
print("Capitalized:", capitalize_array)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalized: ['Python' 'Numpy' 'Pandas']


6. ** Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [17]:
import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)
print("Words with spaces:", spaced_words)


Words with spaces: ['p y t h o n' 'n u m p y' 'p a n d a s']


7. ** Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [19]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2
print("Element-wise Addition:\n", addition)

# Element-wise subtraction
subtraction = array1 - array2
print("\nElement-wise Subtraction:\n", subtraction)

# Element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise Multiplication:\n", multiplication)

# Element-wise division
division = array1 / array2
print("\nElement-wise Division:\n", division)


Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. ** Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [20]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Step 2: Extract diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


9. ** Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array**

In [21]:
import numpy as np

# Step 1: Generate an array of 100 random integers between 0 and 1000
array = np.random.randint(0, 1001, size=100)
print("Random Array:\n", array)

# Step 2: Define a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

# Step 3: Apply the is_prime function to filter prime numbers
prime_numbers = [num for num in array if is_prime(num)]

print("\nPrime Numbers in the Array:", prime_numbers)


Random Array:
 [  8 606 300 781 412 829 848 397 737 289  96 506 112 130 144 399 815 539
 339 917 659  10 669 781 948 375 772 338 122 887 859 102 427 369 695 622
 600 514 777 269 801 338 286  75  23 514 788 603 752 107 362 242   4 981
   0 192 213 430 845 433 478 825 263 121 893 302 431 784 692  97 615  21
 158 497 486 849 606 960 364 904 638 165 735 393 471  49 410 790 190 424
 865 720 239 369 670 608 382 534 303 181]

Prime Numbers in the Array: [829, 397, 659, 887, 859, 269, 23, 107, 433, 263, 431, 97, 239, 181]


10. ** Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

In [24]:
temperatures = [40, 42, 44, 40, 39, 46, 45]

# Number of temperature readings
n = len(temperatures)

# Summation
sum = 0.0
for temp in temperatures:
    sum += temp

# Average Calculation
average = sum / n

# Output
print(f"Average Temperature: {average} degrees Celsius")

Average Temperature: 42.285714285714285 degrees Celsius
